/* Build step (run by the deploy Action, not needed locally): bakes the a11y/SEO
   outline into index.html's #a11y element so non-JS crawlers get it. The outline
   itself is generated by a11y.js — the same module orrery.js uses at runtime. */
const fs = require('fs');

let src = fs.readFileSync('content.js', 'utf8').replace('const SITE', 'globalThis.SITE');
eval(src);
const a11yOutline = require('./a11y.js');
const h = a11yOutline(SITE);

let html = fs.readFileSync('index.html', 'utf8');
const marker = /<main id="a11y" class="sr-only">[\s\S]*?<\/main>/;
if (!marker.test(html)) { console.error('prerender: #a11y marker not found in index.html'); process.exit(1); }
html = html.replace(marker, '<main id="a11y" class="sr-only">' + h + '</main>');
fs.writeFileSync('index.html', html);
console.log('prerendered a11y outline into index.html (' + h.length + ' chars)');
